import streamlit as st
import pandas as pd
import random

st.set_page_config(page_title="System Observability", layout="wide")

st.title("📊 System Observability & RAGAS Metrics")
st.caption("Monitor retrieval performance and identify library gaps for future ingestion.")

# --- RAGAS Metrics (Simulated/Pre-computed for Dashboard) ---
# In production, this would load from a data/evals/results.json file generated by a background job
st.markdown("### 🎯 Retrieval Performance (Latest Batch)")

m1, m2, m3, m4, m5 = st.columns(5)
m1.metric("Faithfulness", "0.92", "+0.04", help="Is the answer grounded strictly in the retrieved snippets?")
m2.metric("Answer Relevance", "0.88", "+0.02", help="Does the answer directly address the user's prompt?")
m3.metric("Context Precision", "0.85", "-0.01", help="Are the most relevant chunks ranked at the top?")
m4.metric("Context Recall", "0.95", "+0.05", help="Did we find all the relevant information present in the library?")
m5.metric("Answer Correctness", "0.90", "+0.03", help="End-to-end quality and semantic accuracy.")

st.markdown("---")

# --- Library Gaps (Out of Scope Queries) ---
st.markdown("### 🕳️ Library Knowledge Gaps")
st.caption("These queries were safely routed to the 'out_of_scope' node. Use this data to decide which books to ingest next.")

gaps_data = st.session_state.get("gaps_log", [])

if not gaps_data:
    st.info("No library gaps detected in the current session.")
else:
    # Convert list of dicts to DataFrame and count frequencies
    df_gaps = pd.DataFrame(gaps_data)
    df_grouped = df_gaps.groupby('query').size().reset_index(name='frequency')
    df_grouped = df_grouped.sort_values(by='frequency', ascending=False)
    
    st.dataframe(df_grouped, use_container_width=True, hide_index=True)


# # Extract out-of-scope queries from the chat history
# gaps = [
#     msg["content"] for msg in st.session_state.get("messages", []) 
#     if msg["role"] == "user" and "out of scope" in str(msg).lower() # Simplified check for UI purposes
# ]

# # For demo purposes, let's inject some standard gaps if none exist
# if not gaps:
#     demo_gaps = [
#         {"query": "What are the best exercises for hypertrophy?", "detected_domain": "Health/Fitness", "frequency": 14},
#         {"query": "How do I fix a leaky faucet?", "detected_domain": "Home Repair", "frequency": 5},
#         {"query": "Explain the plot of Dune.", "detected_domain": "Sci-Fi Fiction", "frequency": 8}
#     ]
#     df_gaps = pd.DataFrame(demo_gaps)
# else:
#     df_gaps = pd.DataFrame({"query": gaps, "detected_domain": "Unknown", "frequency": 1})

# st.dataframe(df_gaps, use_container_width=True, hide_index=True)